services:
  backend:
    image: hellsfoul/girodecoder-backend
    ports:
      - "8080:8080"
    networks:
      - girodecoder-network

  frontend:
    image: hellsfoul/girodecoder-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - girodecoder-network

networks:
  girodecoder-network:
    driver: bridge